### ISSUE TITLE
License issue of BinaryNinja

### ISSUE THREAD

**Issue by nav60** [evandowning/deepreflect#4]
Hi,
Sir. I am getting error of BinaryNinja however i have it in the binja_setup directory. Docker commands were not working. so i am trying to use binja.y file to see the extraction step.
As you answer me in my previous question about IDA Pro usage instead of BinaryNinja tool. Sir, can i perform the same extraction using IDA-PRO. I mean to say, same features can be extracted using any other tool. I know i have to modify the code for this step because of this license issue. 

_dr$python3 binja.py --exe /data/benign_unpacked/benign/w64.exe --output /data/benign_unpacked_raw//benign/w64.exe.bndb_

Traceback (most recent call last):
  File "binja.py", line 51, in <module>
    _main()
  File "binja.py", line 35, in _main
    bv = BinaryViewType.get_view_of_file(fn)
  File "/home/naveed/Desktop/deepreflect/binja_setup/binaryninja/python/binaryninja/binaryview.py", line 766, in get_view_of_file
    view = BinaryView.open(filename)
  File "/home/naveed/Desktop/deepreflect/binja_setup/binaryninja/python/binaryninja/binaryview.py", line 1382, in open
    binaryninja._init_plugins()
  File "/home/naveed/Desktop/deepreflect/binja_setup/binaryninja/python/binaryninja/__init__.py", line 174, in _init_plugins
    **raise RuntimeError("License is not valid. Please supply a valid license.")
RuntimeError: License is not valid. Please supply a valid license.**

**Comment by evandowning** [comment]
It seems like it's an issue with your BinaryNinja license, not with DeepReflect.

You can of course modify my scripts to use IDA Pro instead of BinaryNinja.
I'll happily accept a pull request if you do so.
